"""Tests for gcode_compat — generic slicer G-code → BBL firmware translation."""

from bambox.gcode_compat import (
    _build_header_block,
    _compute_flush_lengths,
    _parse_prusa_time,
    is_bbl_gcode,
    rewrite_tool_changes,
    translate_to_bbl,
)

# --- is_bbl_gcode ---


def test_orca_gcode_detected():
    gcode = b"; HEADER_BLOCK_START\n; total layer number: 50\n; HEADER_BLOCK_END\n"
    assert is_bbl_gcode(gcode) is True


def test_cura_gcode_not_bbl():
    gcode = b";FLAVOR:Marlin\n;LAYER_COUNT:50\n;LAYER:0\n"
    assert is_bbl_gcode(gcode) is False


def test_prusa_gcode_not_bbl():
    gcode = b"; generated by PrusaSlicer\n;LAYER_CHANGE\n;HEIGHT:0.2\n"
    assert is_bbl_gcode(gcode) is False


def test_accepts_str():
    assert is_bbl_gcode("; HEADER_BLOCK_START\n; total layer number: 1\n") is True


# --- translate_to_bbl (passthrough) ---


def test_bbl_gcode_unchanged():
    gcode = b"; HEADER_BLOCK_START\n; total layer number: 50\n; HEADER_BLOCK_END\nG28\n"
    assert translate_to_bbl(gcode) == gcode


# --- translate_to_bbl (CuraEngine) ---


CURA_GCODE = (
    b";FLAVOR:Marlin\n"
    b";TIME:338\n"
    b";Filament used: 0.33m\n"
    b";Layer height: 0.2\n"
    b";MAXZ:10\n"
    b";TARGET_MACHINE.NAME:BambuLab P1S\n"
    b"\n"
    b";LAYER_COUNT:3\n"
    b";LAYER:0\n"
    b"G1 Z0.2 F3000\n"
    b"G1 X10 Y10 E1\n"
    b";LAYER:1\n"
    b"G1 Z0.4\n"
    b";LAYER:2\n"
    b"G1 Z0.6\n"
)


def test_cura_header_block():
    result = translate_to_bbl(CURA_GCODE).decode()
    assert result.startswith("; HEADER_BLOCK_START\n")
    assert "; HEADER_BLOCK_END\n" in result
    assert "; total layer number: 3" in result
    assert "; max_z_height: 10" in result
    assert "; total estimated time: 5m 38s" in result


def test_cura_layer_markers():
    result = translate_to_bbl(CURA_GCODE).decode()

    # Layer 0 → 1/3
    assert "; layer num/total_layer_count: 1/3" in result
    assert "M73 L1\n" in result
    assert "M991 S0 P0 ;notify layer change" in result

    # Layer 2 → 3/3
    assert "; layer num/total_layer_count: 3/3" in result
    assert "M73 L3\n" in result
    assert "M991 S0 P2 ;notify layer change" in result


def test_cura_progress_commands():
    """M73 P{pct} R{remaining_min} injected at each layer."""
    result = translate_to_bbl(CURA_GCODE).decode()
    # Layer 0: 0% done, full time remaining (338s ≈ 6min)
    assert "M73 P0 R6\n" in result
    # Layer 1: 33% done
    assert "M73 P33 R4\n" in result
    # Layer 2: 67% done
    assert "M73 P67 R2\n" in result


def test_cura_original_markers_preserved():
    result = translate_to_bbl(CURA_GCODE).decode()
    assert ";LAYER_COUNT:3" in result
    assert ";LAYER:0" in result
    assert ";LAYER:2" in result


def test_cura_movement_preserved():
    result = translate_to_bbl(CURA_GCODE).decode()
    assert "G1 Z0.2 F3000" in result
    assert "G1 X10 Y10 E1" in result


# --- translate_to_bbl (PrusaSlicer) ---


PRUSA_GCODE = (
    b"; generated by PrusaSlicer 2.7.0\n"
    b"; estimated printing time (normal mode) = 1h 5m 30s\n"
    b";LAYER_CHANGE\n"
    b";HEIGHT:0.2\n"
    b"G1 Z0.2 F3000\n"
    b";LAYER_CHANGE\n"
    b";HEIGHT:0.4\n"
    b"G1 Z0.4\n"
    b";LAYER_CHANGE\n"
    b";HEIGHT:0.6\n"
    b"G1 Z0.6\n"
)


def test_prusa_header_block():
    result = translate_to_bbl(PRUSA_GCODE).decode()
    assert result.startswith("; HEADER_BLOCK_START\n")
    assert "; total layer number: 3" in result
    assert "; max_z_height: 0.6" in result
    assert "; total estimated time: 1h 5m 30s" in result


def test_prusa_layer_markers():
    result = translate_to_bbl(PRUSA_GCODE).decode()
    assert "; layer num/total_layer_count: 1/3" in result
    assert "M73 L1\n" in result
    assert "M991 S0 P0 ;notify layer change" in result
    assert "; layer num/total_layer_count: 3/3" in result
    assert "M73 L3\n" in result


def test_prusa_progress_commands():
    """M73 P{pct} R{remaining_min} injected at each layer."""
    result = translate_to_bbl(PRUSA_GCODE).decode()
    # Layer 0: 0% done, full time remaining (3930s ≈ 66min)
    assert "M73 P0 R66\n" in result
    # Layer 2: 67% done
    assert "M73 P67 R22\n" in result


def test_prusa_original_markers_preserved():
    result = translate_to_bbl(PRUSA_GCODE).decode()
    assert ";LAYER_CHANGE" in result
    assert ";HEIGHT:0.2" in result


# --- Z-change fallback (unknown slicer) ---


def test_zchange_plain_gcode_gets_layer_markers():
    """Plain G-code with Z moves and no slicer comments should get layer markers."""
    gcode = b"G28\nG1 X0 Y0 Z0.2 F3000\nG1 X10 Y10 E1\nG1 Z0.4\nG1 X20 Y20 E2\nG0 Z0.6\nG1 X30 E3\n"
    result = translate_to_bbl(gcode).decode()
    assert result.startswith("; HEADER_BLOCK_START\n")
    assert "; total layer number: 3" in result
    assert "; max_z_height: 0.60" in result
    assert "M73 L1\n" in result
    assert "M73 L2\n" in result
    assert "M73 L3\n" in result
    assert "M991 S0 P0 ;notify layer change" in result
    assert "M991 S0 P2 ;notify layer change" in result
    # Original movement commands preserved
    assert "G1 X10 Y10 E1" in result


def test_zchange_no_z_moves_unchanged():
    """G-code with no Z moves should be returned unchanged."""
    gcode = b"G28\nG1 X10 Y10 E1 F300\nG1 X20 Y20 E2\n"
    assert translate_to_bbl(gcode) == gcode


def test_zchange_mixed_g0_g1():
    """Both G0 and G1 Z changes should be detected."""
    gcode = b"G1 Z0.2 F3000\nG0 Z0.4\nG1 Z0.6\n"
    result = translate_to_bbl(gcode).decode()
    assert "; total layer number: 3" in result
    assert "M73 L1\n" in result
    assert "M73 L2\n" in result
    assert "M73 L3\n" in result


def test_zchange_z_decrease_not_counted():
    """Z decreases (e.g. retract or Z-hop return) should not count as new layers."""
    gcode = b"G1 Z0.2 F3000\nG1 Z0.4\nG1 Z0.3\nG1 Z0.6\n"
    result = translate_to_bbl(gcode).decode()
    # Z0.3 < Z0.4 so not a new layer; only 0.2, 0.4, 0.6 count
    assert "; total layer number: 3" in result


def test_zchange_does_not_fire_for_cura():
    """Fallback must not fire when CuraEngine markers are present."""
    result = translate_to_bbl(CURA_GCODE).decode()
    # Should use Cura path (has ;LAYER_COUNT:3), not zchange
    assert ";LAYER_COUNT:3" in result
    assert "; total layer number: 3" in result


def test_zchange_does_not_fire_for_prusa():
    """Fallback must not fire when PrusaSlicer markers are present."""
    result = translate_to_bbl(PRUSA_GCODE).decode()
    assert ";LAYER_CHANGE" in result
    assert "; total layer number: 3" in result


def test_zchange_progress_percentage():
    """Progress percentage should increase with each layer."""
    gcode = b"G1 Z0.2\nG1 Z0.4\nG1 Z0.6\nG1 Z0.8\n"
    result = translate_to_bbl(gcode).decode()
    assert "M73 P0 R0\n" in result  # layer 0
    assert "M73 P25 R0\n" in result  # layer 1
    assert "M73 P50 R0\n" in result  # layer 2
    assert "M73 P75 R0\n" in result  # layer 3


# --- Helpers ---


def test_build_header_block():
    block = _build_header_block(50, 338, "10")
    assert "; HEADER_BLOCK_START" in block
    assert "; total layer number: 50" in block
    assert "; total estimated time: 5m 38s" in block
    assert "; max_z_height: 10" in block
    assert "; HEADER_BLOCK_END" in block


def test_build_header_block_hours():
    block = _build_header_block(100, 3661, "20")
    assert "1h 1m 1s" in block


def test_parse_prusa_time():
    assert _parse_prusa_time("1h 5m 30s") == 3930
    assert _parse_prusa_time("23m 10s") == 1390
    assert _parse_prusa_time("45s") == 45
    assert _parse_prusa_time("2h 0m 0s") == 7200


# --- Integration: pack_gcode_3mf auto-translates ---


def test_pack_auto_translates_cura(tmp_path):
    """pack_gcode_3mf automatically translates CuraEngine G-code."""
    import zipfile

    from bambox import pack_gcode_3mf

    out = tmp_path / "test.gcode.3mf"
    pack_gcode_3mf(CURA_GCODE, out)

    with zipfile.ZipFile(out) as z:
        inner = z.read("Metadata/plate_1.gcode").decode()
        assert inner.startswith("; HEADER_BLOCK_START")
        assert "; total layer number: 3" in inner
        assert "M73 L1\n" in inner
        assert "M991 S0 P0" in inner


def test_pack_no_double_translate(tmp_path):
    """pack_gcode_3mf does not double-translate BBL G-code."""
    import zipfile

    from bambox import pack_gcode_3mf

    bbl_gcode = b"; HEADER_BLOCK_START\n; total layer number: 2\n; HEADER_BLOCK_END\nG28\nG1 Z0.2\n"
    out = tmp_path / "test.gcode.3mf"
    pack_gcode_3mf(bbl_gcode, out)

    with zipfile.ZipFile(out) as z:
        inner = z.read("Metadata/plate_1.gcode").decode()
        # Should appear exactly once
        assert inner.count("; HEADER_BLOCK_START") == 1


# --- rewrite_tool_changes ---


MULTI_TOOL_GCODE = (
    "G28\nG1 Z0.2 F3000\nG1 X10 Y10 E1 F600\nT1\nG1 X20 Y20 E2 F600\nT0\nG1 X30 Y30 E3 F600\n"
)

BASIC_SETTINGS: dict[str, object] = {
    "nozzle_temperature": ["220", "260"],
    "filament_max_volumetric_speed": ["12", "15"],
    "retract_length_toolchange": ["2", "2"],
    "z_hop_types": ["0", "0", "0", "0", "0"],
    "long_retractions_when_cut": ["0", "0", "0", "0", "0"],
    "retraction_distances_when_cut": ["18", "18", "18", "18", "18"],
    "nozzle_temperature_range_high": ["240", "280", "240", "240", "240"],
    "filament_type": ["PLA", "PETG-CF", "PLA", "PLA", "PLA"],
    "default_acceleration": "10000",
    "initial_layer_acceleration": "500",
    "initial_layer_print_height": "0.2",
    "flush_volumes_matrix": [
        "0",
        "280",
        "280",
        "280",
        "280",
        "0",
        "280",
        "280",
        "280",
        "280",
        "0",
        "280",
        "280",
        "280",
        "280",
        "0",
    ],
    "flush_multiplier": "0.3",
}


def test_rewrite_replaces_t_commands():
    """T commands should be replaced with M620/M621 sequences."""
    result = rewrite_tool_changes(MULTI_TOOL_GCODE, BASIC_SETTINGS)
    # M620/M621 sequences should be present (wrapping the T commands)
    assert "M620 S1A" in result  # first tool change to T1
    assert "M621 S1A" in result
    assert "M620 S0A" in result  # second tool change back to T0
    assert "M621 S0A" in result
    # The output should be significantly larger than input (toolchange templates added)
    assert len(result) > len(MULTI_TOOL_GCODE) * 5


def test_rewrite_preserves_original_gcode():
    """Original movement commands should be preserved."""
    result = rewrite_tool_changes(MULTI_TOOL_GCODE, BASIC_SETTINGS)
    assert "G1 X10 Y10 E1 F600" in result
    assert "G1 X20 Y20 E2 F600" in result
    assert "G1 X30 Y30 E3 F600" in result


def test_rewrite_no_tool_changes():
    """G-code with no T commands should be returned unchanged."""
    gcode = "G28\nG1 Z0.2 F3000\nG1 X10 Y10 E1 F600\n"
    result = rewrite_tool_changes(gcode, BASIC_SETTINGS)
    assert result == gcode


def test_rewrite_skips_t255():
    """T255 (AMS retract) should not be rewritten."""
    gcode = "G28\nT255\nG1 X10 Y10\n"
    result = rewrite_tool_changes(gcode, BASIC_SETTINGS)
    assert "T255" in result
    assert "M620" not in result


def test_rewrite_two_changes_have_correct_extruders():
    """First change: 0→1, second change: 1→0."""
    result = rewrite_tool_changes(MULTI_TOOL_GCODE, BASIC_SETTINGS)
    # The M620/M621 commands should reference the correct extruder
    m620_matches = list(__import__("re").finditer(r"M620 S(\d+)A", result))
    assert len(m620_matches) == 2
    assert m620_matches[0].group(1) == "1"  # first change: switch TO 1
    assert m620_matches[1].group(1) == "0"  # second change: switch TO 0


def test_rewrite_uses_temperatures_from_settings():
    """Rendered toolchange should reference filament temperatures."""
    result = rewrite_tool_changes(MULTI_TOOL_GCODE, BASIC_SETTINGS)
    # The toolchange template uses nozzle_temperature_range_high for flush temp
    # For first change (→extruder 1), should see 280 (PETG-CF range high)
    assert "280" in result


def test_compute_flush_lengths_from_matrix():
    """Flush lengths should be computed from flush_volumes_matrix * multiplier."""
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(BASIC_SETTINGS, 0, 1)
    total = fl1 + fl2 + fl3 + fl4
    # 280 * 0.3 = 84 mm³ / ~2.405 mm² ≈ 34.9 mm total
    assert 34.0 < total < 36.0
    # Same-filament transition should have zero flush
    fl1z, fl2z, fl3z, fl4z = _compute_flush_lengths(BASIC_SETTINGS, 0, 0)
    assert fl1z + fl2z + fl3z + fl4z == 0.0


def test_compute_flush_lengths_defaults_without_matrix():
    """Without a matrix, should fall back to default 280 mm³."""
    settings: dict[str, object] = {}
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(settings, 0, 1)
    total = fl1 + fl2 + fl3 + fl4
    # 280 * 0.3 = 84 mm³ / ~2.405 mm² ≈ 34.9 mm
    assert 34.0 < total < 36.0


def test_rewrite_detects_initial_extruder():
    """If G-code starts with T1 before the first tool change, previous_ext should be 1."""
    gcode = "G28\nT1\nG1 Z0.2 F3000\nG1 X10 Y10 E1 F600\nT0\nG1 X20 Y20 E2 F600\n"
    result = rewrite_tool_changes(gcode, BASIC_SETTINGS)
    # Only one tool change (T0), so only one M620/M621 pair
    m620_matches = list(__import__("re").finditer(r"M620 S(\d+)A", result))
    assert len(m620_matches) == 1
    assert m620_matches[0].group(1) == "0"  # switching TO 0 (from 1)


# --- Cura edge cases (uncovered lines) ---


def test_cura_no_layer_count_returns_unchanged():
    """Cura path with no ;LAYER_COUNT: should return text unchanged (line 86)."""
    gcode = b";FLAVOR:Marlin\n;LAYER:0\nG1 Z0.2\n"
    # Has ;LAYER: but not ;LAYER_COUNT:, so _translate_cura returns early
    # However translate_to_bbl routes to zchange fallback, not _translate_cura
    # Test _translate_cura directly
    from bambox.gcode_compat import _translate_cura

    text = gcode.decode()
    result = _translate_cura(text)
    assert result == text


def test_cura_with_time_elapsed():
    """Cura G-code with TIME_ELAPSED uses accurate per-layer timing (lines 92, 105, 128)."""
    gcode = (
        b";LAYER_COUNT:3\n"
        b";TIME:6666\n"
        b";Layer height: 0.2\n"
        b";MAXZ:0.6\n"
        b";LAYER:0\n"
        b"G1 Z0.2\n"
        b";TIME_ELAPSED:10.5\n"
        b";LAYER:1\n"
        b"G1 Z0.4\n"
        b";TIME_ELAPSED:20.0\n"
        b";LAYER:2\n"
        b"G1 Z0.6\n"
        b";TIME_ELAPSED:30.0\n"
    )
    result = translate_to_bbl(gcode).decode()
    # Should use last TIME_ELAPSED (30s) as total time, not ;TIME:6666
    assert "; total estimated time: 0m 30s" in result
    # Layer markers should be present
    assert "M73 L1\n" in result


def test_cura_negative_maxz_uses_layer_height():
    """Cura with negative/zero MAXZ computes from layer count (lines 112-114)."""
    gcode = (
        b";LAYER_COUNT:5\n;Layer height: 0.2\n;MAXZ:-2.14748e+06\n;TIME:100\n;LAYER:0\nG1 Z0.2\n"
    )
    result = translate_to_bbl(gcode).decode()
    # 5 layers * 0.2mm = 1.0
    assert "; max_z_height: 1.0" in result


def test_cura_no_maxz_no_layer_height():
    """Cura with no MAXZ and no layer height uses 0.2 default (line 113)."""
    gcode = b";LAYER_COUNT:10\n;TIME:100\n;LAYER:0\nG1 Z0.2\n"
    result = translate_to_bbl(gcode).decode()
    # 10 layers * 0.2 default = 2.0
    assert "; max_z_height: 2.0" in result


def test_cura_total_zero_layers():
    """Edge case: total=0 should not divide by zero (line 132)."""
    from bambox.gcode_compat import _translate_cura

    # Construct text that has LAYER_COUNT:0
    text = ";LAYER_COUNT:0\n;TIME:100\n;MAXZ:1.0\n;LAYER:0\nG1 Z0.2\n"
    result = _translate_cura(text)
    # Should not crash, layer 0 should get 0% progress
    assert "M73 P0" in result


# --- Prusa edge cases ---


def test_prusa_no_time_estimate():
    """Prusa G-code without time estimate should use 0 (line 158/162)."""
    gcode = b"; generated by PrusaSlicer\n;LAYER_CHANGE\n;HEIGHT:0.2\nG1 Z0.2\n"
    result = translate_to_bbl(gcode).decode()
    assert "; total estimated time: 0m 0s" in result


def test_prusa_maxz_from_last_height():
    """Prusa without ;MAXZ: uses last ;HEIGHT: value (line 170)."""
    gcode = (
        b"; generated by PrusaSlicer\n"
        b";LAYER_CHANGE\n;HEIGHT:0.2\nG1 Z0.2\n"
        b";LAYER_CHANGE\n;HEIGHT:0.4\nG1 Z0.4\n"
        b";LAYER_CHANGE\n;HEIGHT:3.6\nG1 Z3.6\n"
    )
    result = translate_to_bbl(gcode).decode()
    assert "; max_z_height: 3.6" in result


# --- _num / _arr helper edge cases (lines 302-308) ---


def test_rewrite_handles_none_values_in_settings():
    """_num should handle None values gracefully (line 304-305)."""
    settings: dict[str, object] = {
        **BASIC_SETTINGS,
        "nozzle_temperature": [None, None],  # type: ignore[list-item]
    }
    gcode = "G28\nG1 Z0.2 F3000\nG1 X10 Y10 E1 F600\nT1\nG1 X20 Y20 E2\n"
    # Should not crash — _num returns default for None
    result = rewrite_tool_changes(gcode, settings)
    assert "M620 S1A" in result


def test_rewrite_handles_non_numeric_string_in_settings():
    """_num should handle non-numeric strings gracefully (lines 300-303)."""
    settings: dict[str, object] = {
        **BASIC_SETTINGS,
        "nozzle_temperature": ["not_a_number", "also_nan"],
    }
    gcode = "G28\nG1 Z0.2 F3000\nG1 X10 Y10 E1 F600\nT1\nG1 X20 Y20 E2\n"
    result = rewrite_tool_changes(gcode, settings)
    assert "M620 S1A" in result


# --- _compute_flush_lengths edge cases ---


def test_compute_flush_nonsquare_matrix():
    """Non-square matrix should fall back to default volume (lines 442-445)."""
    settings: dict[str, object] = {
        "flush_volumes_matrix": ["100", "200", "300"],  # 3 elements, not square
        "flush_multiplier": "0.3",
    }
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(settings, 0, 1)
    total = fl1 + fl2 + fl3 + fl4
    # Should use default 280 * 0.3
    assert 34.0 < total < 36.0


def test_compute_flush_out_of_range_extruder():
    """Extruder index out of matrix range falls back to default (line 444)."""
    settings: dict[str, object] = {
        "flush_volumes_matrix": ["0", "100", "200", "0"],  # 2x2
        "flush_multiplier": "0.3",
    }
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(settings, 5, 0)  # from_ext=5 > n=2
    total = fl1 + fl2 + fl3 + fl4
    assert 34.0 < total < 36.0


def test_compute_flush_invalid_multiplier():
    """Invalid flush_multiplier string should fall back to 0.3 (lines 452-453)."""
    settings: dict[str, object] = {
        "flush_volumes_matrix": ["0", "280", "280", "0"],
        "flush_multiplier": "not_a_number",
    }
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(settings, 0, 1)
    total = fl1 + fl2 + fl3 + fl4
    # 280 * 0.3 default
    assert 34.0 < total < 36.0


def test_compute_flush_invalid_matrix_value():
    """Non-numeric matrix value should fall back to default (line 442-443)."""
    settings: dict[str, object] = {
        "flush_volumes_matrix": ["bad", "bad", "bad", "bad"],
        "flush_multiplier": "0.3",
    }
    fl1, fl2, fl3, fl4 = _compute_flush_lengths(settings, 0, 1)
    total = fl1 + fl2 + fl3 + fl4
    assert 34.0 < total < 36.0


# --- _coerce_array edge cases ---


def test_coerce_array_non_list():
    """Non-list value should be broadcast to 5-element list (line 472)."""
    from bambox.gcode_compat import _coerce_array

    result = _coerce_array(42)
    assert result == [42, 42, 42, 42, 42]


def test_coerce_array_string_elements():
    """String elements should be coerced to numbers where possible (lines 476-482)."""
    from bambox.gcode_compat import _coerce_array

    result = _coerce_array(["10", "3.5", "hello"])
    assert result[0] == 10  # int
    assert result[1] == 3.5  # float
    assert result[2] == "hello"  # not a number, kept as string


def test_coerce_array_non_string_non_numeric():
    """Non-string, non-numeric elements should pass through (line 484)."""
    from bambox.gcode_compat import _coerce_array

    result = _coerce_array([None, True, [1, 2]])
    assert result == [None, True, [1, 2]]
